### ISSUE TITLE
infografia..

### ISSUE THREAD

**Issue by 17ferruiz** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-17ferruiz#2]
[Fernanda (1).pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-17ferruiz/files/11084762/Fernanda.1.pdf)

**Comment by Arlet04** [comment]
Partes de infografía: falta agregar fuentes 3
Coherencia:excelente 4
Organización: excelente 4  
Diseño: excelente 4
Creatividad: excelente 4
Puntos:19/20
Calificación: 19 / 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
